using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using RailDispatchMono.Core.Game.Building;
using RailDispatchMono.Core.Game.Debug;
using RailDispatchMono.Core.Game.Map;
using RailDispatchMono.Core.Game.Railway;
using RailDispatchMono.Core.Game.Rendering;
using RailDispatchMono.Core.Game.Train;
using RailDispatchMono.Core.ScreenManagers;
using System;
using System.Collections.Generic;
using System.Linq;

namespace RailDispatchMono.Core.Screens.UI
{
    public class InputManager
    {
        private readonly GraphicsDevice _graphicsDevice; private readonly SpriteBatch _spriteBatch; private readonly Camera _camera; private readonly TrackBuilder _builder; private readonly ScreenManager _screenManager; private readonly TrackRenderer _renderer; private readonly TrainManager _trainManager; private readonly TrainRenderer _trainRenderer; private readonly JunctionRadialMenu _junctionRadialMenu; private readonly GameMap _map; private readonly SignalController _signalController; private readonly SignalRadialMenu _signalRadialMenu; private readonly SignalDirectionMenu _signalDirectionMenu; private readonly SignalSelectionMenu _signalSelectionMenu; private readonly StationController _stationController; private readonly StationRenderer _stationRenderer; private readonly DepotController _depotController; private readonly DepotRenderer _depotRenderer; private readonly SignalRenderer _signalRenderer; private readonly WagonRouteMenu _wagonRouteMenu; private readonly DepotTrainMenu _depotTrainMenu;
        private SpriteFont? _tooltipFont; private Texture2D? _tooltipPixel; private MouseState _previousMouse; private KeyboardState _previousKeyboard; private int _previousScrollWheelValue; private bool _wagonRouteEditMode; private bool _spawnArmed;
        private int _selectedPassengerWagons = 2;
        private int _stationWidth = 1, _stationHeight = 1; private static readonly (int Width, int Height)[] StationSizes = { (1,1),(2,2),(3,3),(4,4) }; private int _stationSizeIndex;
        public event Action<Depot>? DepotSelected;

        public InputManager(GraphicsDevice graphicsDevice, SpriteBatch spriteBatch, Camera camera, TrackBuilder builder, TrackRenderer renderer, TrainManager trainManager, TrainRenderer trainRenderer, JunctionRadialMenu junctionRadialMenu, SignalController signalController, SignalRadialMenu signalRadialMenu, ScreenManager screenManager, SignalDirectionMenu signalDirectionMenu, SignalSelectionMenu signalSelectionMenu, GameMap map, DepotController? depotController = null)
        {
            _graphicsDevice=graphicsDevice; _spriteBatch=spriteBatch; _camera=camera; _builder=builder; _renderer=renderer; _trainManager=trainManager; _trainRenderer=trainRenderer; _junctionRadialMenu=junctionRadialMenu; _signalController=signalController; _signalRadialMenu=signalRadialMenu; _signalDirectionMenu=signalDirectionMenu; _screenManager=screenManager; _signalSelectionMenu=signalSelectionMenu; _map=map; _stationController=_trainManager.StationController; _stationRenderer=new StationRenderer(_stationController); _stationRenderer.LoadContent(_graphicsDevice); _depotController=depotController ?? new DepotController(); _depotRenderer=new DepotRenderer(_depotController); _depotRenderer.LoadContent(_graphicsDevice); _previousMouse=Mouse.GetState(); _previousKeyboard=Keyboard.GetState(); _previousScrollWheelValue=_previousMouse.ScrollWheelValue; _signalRenderer=new SignalRenderer(_map,_signalController); _signalRenderer.LoadContent(_graphicsDevice); _signalDirectionMenu.DirectionSelected+=OnDirectionSelected; _wagonRouteMenu=new WagonRouteMenu(_graphicsDevice); _wagonRouteMenu.LoadContent(); _wagonRouteMenu.RouteChanged+=OnWagonRouteChanged; _depotTrainMenu=new DepotTrainMenu(_graphicsDevice); _depotTrainMenu.LoadContent(); _depotTrainMenu.ConsistSelected+=OnConsistSelected;
        }
        private void OnDirectionSelected(object? sender, SignalDirectionMenu.SignalDirectionSelectedEventArgs e)=>_signalController.AddSignal(e.Position,e.Direction);
        private void OnConsistSelected(int passengerWagons){_selectedPassengerWagons=Math.Clamp(passengerWagons,1,8);_spawnArmed=true;_builder.Mode=TrackBuildMode.None;}
        public void SetFont(SpriteFont font){_tooltipFont=font;_wagonRouteMenu.SetFont(font);_depotTrainMenu.SetFont(font);}
        public void Update(GameTime gameTime)
        {
            var mouse=Mouse.GetState(); var keyboard=Keyboard.GetState();
            if(_depotTrainMenu.IsOpen){_depotTrainMenu.Update(mouse);if(IsKeyPressed(keyboard,Keys.Escape))_depotTrainMenu.Close();RememberInput(mouse,keyboard);return;}
            if(_wagonRouteMenu.IsOpen){_wagonRouteMenu.Update(mouse);if(IsKeyPressed(keyboard,Keys.Escape))_wagonRouteMenu.Close();RememberInput(mouse,keyboard);return;}
            if(_junctionRadialMenu.IsOpen){_junctionRadialMenu.Update(mouse,_previousMouse);if(IsKeyPressed(keyboard,Keys.Escape))_junctionRadialMenu.Close();RememberInput(mouse,keyboard);return;} if(_signalRadialMenu.IsOpen){_signalRadialMenu.Update(mouse,_previousMouse);if(IsKeyPressed(keyboard,Keys.Escape))_signalRadialMenu.Close();RememberInput(mouse,keyboard);return;} if(_signalDirectionMenu.IsOpen){_signalDirectionMenu.Update(mouse,_previousMouse);if(IsKeyPressed(keyboard,Keys.Escape))_signalDirectionMenu.Close();RememberInput(mouse,keyboard);return;} if(_signalSelectionMenu.IsOpen){_signalSelectionMenu.Update(mouse,_previousMouse);if(IsKeyPressed(keyboard,Keys.Escape))_signalSelectionMenu.Close();RememberInput(mouse,keyboard);return;}
            if(mouse.MiddleButton==ButtonState.Pressed&&_previousMouse.MiddleButton==ButtonState.Pressed){Vector2 d=new(mouse.X-_previousMouse.X,mouse.Y-_previousMouse.Y);if(_camera.Zoom>0)_camera.Move(-d/_camera.Zoom);} int scroll=mouse.ScrollWheelValue;if(scroll!=_previousScrollWheelValue)_camera.ZoomAt(new Vector2(mouse.X,mouse.Y),scroll>_previousScrollWheelValue?2f:-2f);_previousScrollWheelValue=scroll;HandleKeyboardInput(keyboard);HandleMouseInput(mouse,keyboard);RememberInput(mouse,keyboard);
        }
        private void HandleKeyboardInput(KeyboardState keyboard)
        {
            if(IsKeyPressed(keyboard,Keys.D1)||IsKeyPressed(keyboard,Keys.NumPad1))_builder.Mode=TrackBuildMode.Straight; if(IsKeyPressed(keyboard,Keys.D2)||IsKeyPressed(keyboard,Keys.NumPad2))_builder.Mode=TrackBuildMode.Curve; if(IsKeyPressed(keyboard,Keys.D3)||IsKeyPressed(keyboard,Keys.NumPad3))_builder.Mode=TrackBuildMode.Junction; if(IsKeyPressed(keyboard,Keys.D4)||IsKeyPressed(keyboard,Keys.NumPad4))_builder.Mode=TrackBuildMode.Signal; if(IsKeyPressed(keyboard,Keys.D5)||IsKeyPressed(keyboard,Keys.NumPad5))_builder.Mode=TrackBuildMode.Station; if(IsKeyPressed(keyboard,Keys.D9)||IsKeyPressed(keyboard,Keys.NumPad9))_builder.Mode=TrackBuildMode.Depot;
            if(IsKeyPressed(keyboard,Keys.S)){_wagonRouteEditMode=!_wagonRouteEditMode;_builder.Mode=TrackBuildMode.None;_spawnArmed=false;if(!_wagonRouteEditMode)_wagonRouteMenu.Close();}
            if(IsKeyPressed(keyboard,Keys.F1))DebugManager.ToggleCategory(DebugManager.DebugCategory.Block);if(IsKeyPressed(keyboard,Keys.F2))DebugManager.ToggleCategory(DebugManager.DebugCategory.Signal);if(IsKeyPressed(keyboard,Keys.F3))DebugManager.ToggleCategory(DebugManager.DebugCategory.Train);if(IsKeyPressed(keyboard,Keys.F4))DebugManager.ToggleCategory(DebugManager.DebugCategory.TrainMovement);if(IsKeyPressed(keyboard,Keys.F5))ToggleAllDebugCategories();if(IsKeyPressed(keyboard,Keys.F12)){string f=$"debug_log_{DateTime.Now:yyyy-MM-dd_HH-mm-ss}.txt";DebugManager.SaveLogToFile(f);}
            if(IsKeyPressed(keyboard,Keys.Escape)){if(_wagonRouteEditMode){_wagonRouteEditMode=false;_wagonRouteMenu.Close();}else if(_spawnArmed)_spawnArmed=false;else _screenManager.AddScreen(new PauseScreen(),null);} if(IsKeyPressed(keyboard,Keys.R)){if(_builder.Mode==TrackBuildMode.Straight)_builder.StraightHorizontal=!_builder.StraightHorizontal;else if(_builder.Mode==TrackBuildMode.Curve)_builder.Curve=(CurveDirection)(((int)_builder.Curve+1)%4);else if(_builder.Mode==TrackBuildMode.Junction)_builder.Junction=(JunctionType)(((int)_builder.Junction+1)%8);else if(_builder.Mode==TrackBuildMode.Station){_stationSizeIndex=(_stationSizeIndex+1)%StationSizes.Length;(_stationWidth,_stationHeight)=StationSizes[_stationSizeIndex];}} if(IsKeyPressed(keyboard,Keys.J))ToggleSignalOrSwitch();
        }
        private void ToggleAllDebugCategories(){bool all=true;foreach(DebugManager.DebugCategory c in Enum.GetValues(typeof(DebugManager.DebugCategory))){if(c==DebugManager.DebugCategory.All||c==DebugManager.DebugCategory.General)continue;if(!DebugManager.IsCategoryEnabled(c)){all=false;break;}}if(all)DebugManager.DisableAll();else DebugManager.EnableAll();}
        private void ToggleSignalOrSwitch(){var m=Mouse.GetState();var p=ToMapPosition(new Vector2(m.X,m.Y));var s=_signalController.GetSignalsAt(p);if(s.Count>0){foreach(var x in s)x.SetAspect(x.Aspect==SignalAspect.Stop?SignalAspect.Clear:SignalAspect.Stop);return;}if(_map.TryGetTrack(p,out var t)&&t!=null&&t.IsJunction)t.ToggleSwitch();}
        private void HandleMouseInput(MouseState mouse,KeyboardState keyboard)
        {
            Vector2 screen=new(mouse.X,mouse.Y);MapPosition p=ToMapPosition(screen);bool shift=keyboard.IsKeyDown(Keys.LeftShift)||keyboard.IsKeyDown(Keys.RightShift);
            if(mouse.LeftButton==ButtonState.Pressed&&_previousMouse.LeftButton==ButtonState.Released){
                if(_wagonRouteEditMode){var vehicle=_trainRenderer.GetVehicleAtPosition(_trainManager,_camera.ScreenToWorld(screen));if(vehicle.HasValue&&vehicle.Value.train.Composition.Vehicles[vehicle.Value.vehicleIndex] is Wagon wagon){_wagonRouteMenu.Open(screen,wagon,_stationController);return;}return;}
                if(_spawnArmed){if(_map.TryGetTrack(p,out var spawnTrack)&&spawnTrack!=null){SpawnTrain(p,spawnTrack.GetAvailableDirections().FirstOrDefault(),_selectedPassengerWagons);_spawnArmed=false;}return;}
                var depot=_depotController.GetDepotAt(p);if(depot!=null&&_builder.Mode!=TrackBuildMode.Depot){_depotTrainMenu.Open(screen);return;}
                if(_builder.Mode==TrackBuildMode.Signal)PlaceSignal(p,screen);else if(_builder.Mode==TrackBuildMode.Station)PlaceStation(p);else if(_builder.Mode==TrackBuildMode.Depot)PlaceDepot(p);else _builder.BuildAt(p);}
            if(mouse.RightButton==ButtonState.Pressed&&_previousMouse.RightButton==ButtonState.Released){var depot=_depotController.GetDepotAt(p);if(depot!=null){if(shift)_depotController.RemoveDepot(depot);return;}var signals=_signalController.GetSignalsAt(p);if(signals.Count>0){if(shift)_signalController.RemoveSignalsAt(p);else if(signals.Count==1)_signalRadialMenu.Open(screen,signals[0]);else _signalSelectionMenu.Open(screen,signals);return;}var station=_stationController.GetStationAt(p);if(station!=null){if(shift)_stationController.RemoveStation(station);return;}if(_map.TryGetTrack(p,out var track)&&track!=null&&track.IsJunction){if(shift)_builder.Remove(p);else _junctionRadialMenu.Open(screen,track);return;}if(_map.TryGetTrack(p,out var existing)&&existing!=null)_builder.Remove(p);}
        }
        private void PlaceDepot(MapPosition p){var depot=new Depot($"Depot {_depotController.Depots.Count+1}",p);if(_depotController.AddDepot(depot))_builder.Mode=TrackBuildMode.None;}
        private void PlaceSignal(MapPosition p,Vector2 screen){if(!_map.TryGetTrack(p,out var t)||t==null)return;var d=t.GetAvailableDirections();if(d.Count==0)return;if(d.Count==1)_signalController.AddSignal(p,d[0]);else _signalDirectionMenu.Open(screen,p,d);}
        private void PlaceStation(MapPosition p){var o=new MapPosition(p.X-(_stationWidth-1)/2,p.Y-(_stationHeight-1)/2);for(int y=0;y<_stationHeight;y++)for(int x=0;x<_stationWidth;x++){var c=new MapPosition(o.X+x,o.Y+y);if(!_map.TryGetTrack(c,out var t)||t==null||_stationController.GetStationAt(c)!=null)return;}var s=new Station($"Stacja {_stationController.Stations.Count+1}",o,_stationWidth,_stationHeight);_stationController.AddStation(s);}
        private void SpawnTrain(MapPosition cell,TrackConnections direction,int passengerWagons)
        {
            if(direction==TrackConnections.None)direction=TrackConnections.East;
            var locomotiveParameters=new VehicleParameters(25.4f,0.8f,100.0f,80000f,1.0f); var wagonParameters=new VehicleParameters(25.4f,0.8f,100.0f,40000f,1.0f);
            var vehicles=new List<Vehicle>{new Locomotive(LocomotiveType.ElectricDC,locomotiveParameters)};for(int i=0;i<passengerWagons;i++)vehicles.Add(new Wagon(wagonParameters));
            var train=new Train(new Vector2(cell.X+0.5f,cell.Y+0.5f),direction,0f,vehicles);train.SetMap(_map);train.SetSignalController(_signalController);train.SetBlockController(_blockControllerForTrain());_trainManager.Add(train);SaveSchedule(train);
        }
        private BlockController _blockControllerForTrain(){return _trainManager.BlockController ?? new BlockController();}
        private void OnWagonRouteChanged(Wagon wagon){foreach(var train in _trainManager.Trains){if(!train.Composition.Vehicles.Contains(wagon))continue;SaveSchedule(train);break;}}
        private void SaveSchedule(Train train)
        {
            var schedule=new TrainSchedule{TrainId=train.Id};
            for(int i=0;i<train.Composition.Vehicles.Count;i++)if(train.Composition.Vehicles[i] is Wagon wagon)schedule.Wagons.Add(new WagonScheduleEntry{WagonIndex=i,WagonType=wagon.WagonType,StationIds=wagon.Route.StationIds.ToList()});
            try{ScheduleStorage.Save(schedule);}catch(IOException){}
        }
        private MapPosition ToMapPosition(Vector2 p)=>_camera.ScreenToMap(p);private bool IsKeyPressed(KeyboardState k,Keys key)=>k.IsKeyDown(key)&&_previousKeyboard.IsKeyUp(key);private void RememberInput(MouseState m,KeyboardState k){_previousMouse=m;_previousKeyboard=k;_previousScrollWheelValue=m.ScrollWheelValue;}
        public void Draw(GameTime gameTime)
        {
            _graphicsDevice.Clear(Color.CornflowerBlue);var m=Mouse.GetState();Vector2 screen=new(m.X,m.Y);MapPosition p=_camera.ScreenToMap(screen);_spriteBatch.Begin(transformMatrix:_camera.Transform,samplerState:SamplerState.PointClamp);_renderer.Draw(_spriteBatch,_camera);_signalRenderer.Draw(_spriteBatch,_camera);_stationRenderer.Draw(_spriteBatch);_depotRenderer.Draw(_spriteBatch);_trainRenderer.Draw(_spriteBatch,_trainManager);_renderer.DrawPreview(_spriteBatch,p,_builder.Mode,_builder.StraightHorizontal,_builder.Curve,_builder.Junction);if(_builder.Mode==TrackBuildMode.Station)_stationRenderer.DrawPreview(_spriteBatch,p,_stationWidth,_stationHeight);else if(_builder.Mode==TrackBuildMode.Depot)_depotRenderer.DrawPreview(_spriteBatch,p);_spriteBatch.End();DrawStationTooltip(screen,p);DrawWagonTooltip(screen);_spriteBatch.Begin(SpriteSortMode.Deferred,BlendState.AlphaBlend);if(_junctionRadialMenu.IsOpen)_junctionRadialMenu.Draw(_spriteBatch);if(_signalRadialMenu.IsOpen)_signalRadialMenu.Draw(_spriteBatch);if(_signalDirectionMenu.IsOpen)_signalDirectionMenu.Draw(_spriteBatch);if(_signalSelectionMenu.IsOpen)_signalSelectionMenu.Draw(_spriteBatch);_spriteBatch.End();var routeFont=GetTooltipFont();if(routeFont!=null){_wagonRouteMenu.SetFont(routeFont);_depotTrainMenu.SetFont(routeFont);}if(_wagonRouteMenu.IsOpen)_wagonRouteMenu.Draw(_spriteBatch);if(_depotTrainMenu.IsOpen)_depotTrainMenu.Draw(_spriteBatch);
        }
        private void DrawWagonTooltip(Vector2 mouse)
        {
            if(_wagonRouteMenu.IsOpen||_wagonRouteEditMode)return;var world=_camera.ScreenToWorld(mouse);var hit=_trainRenderer.GetVehicleAtPosition(_trainManager,world);if(!hit.HasValue)return;var result=hit.Value;var vehicle=result.train.Composition.Vehicles[result.vehicleIndex];if(vehicle is not Wagon wagon)return;var f=GetTooltipFont();var px=GetTooltipPixel();if(f==null||px==null)return;string route=wagon.Route.IsEmpty?"Trasa: BRAK":$"Trasa: {wagon.Route.StationIds.Count} st.";string next=wagon.Route.NextStationId.HasValue?"Następny: "+wagon.Route.NextStationId.Value.ToString()[..8]:"Następny: -";string[] lines={"WAGON",$"Pociąg: {result.train.Id.ToString()[..8]}",$"Wagon: {result.vehicleIndex + 1}/{result.train.Composition.Vehicles.Count}",$"Pasażerowie: {wagon.PassengerCount}/{wagon.PassengerCapacity}",route,next,"S + LPM: edytuj trasę"};DrawTooltip(mouse,lines,new Color(30,90,150,230));
        }
        private void DrawStationTooltip(Vector2 mouse,MapPosition pos){var s=_stationController.GetStationAt(pos);if(s==null)return;var f=GetTooltipFont();var px=GetTooltipPixel();if(f==null||px==null)return;var waiting=_stationController.Passengers.GetWaitingAt(s).ToList();string[] lines={"STACJA",s.Name,"ID: "+s.Id.ToString()[..8],$"Rozmiar: {s.Width}x{s.Height}","Oczekujacy: "+waiting.Count,"Rozne cele: "+waiting.Select(p=>p.DestinationStation.Id).Distinct().Count(),"Obsluga: "+(s.PassengerServiceEnabled?"TAK":"NIE"),"Postoj: "+s.DwellTimeSeconds.ToString("F1")+" s"};DrawTooltip(mouse,lines,new Color(30,90,150,230));}
        private void DrawTooltip(Vector2 mouse,string[] lines,Color background){var f=GetTooltipFont();var px=GetTooltipPixel();if(f==null||px==null)return;float pad=8f;float lh=f.MeasureString("A").Y*0.75f+3f;float w=lines.Max(x=>f.MeasureString(x).X*0.75f)+pad*2;float h=lines.Length*lh+pad*2;Vector2 tp=mouse+new Vector2(15);var v=_graphicsDevice.Viewport;if(tp.X+w>v.Width)tp.X=mouse.X-w-15;if(tp.Y+h>v.Height)tp.Y=mouse.Y-h-15;_spriteBatch.Begin(SpriteSortMode.Deferred,BlendState.AlphaBlend);Rectangle r=new((int)tp.X,(int)tp.Y,(int)w,(int)h);_spriteBatch.Draw(px,r,background);Vector2 text=tp+new Vector2(pad);for(int i=0;i<lines.Length;i++){_spriteBatch.DrawString(f,lines[i],text,i==0?Color.Yellow:Color.White,0f,Vector2.Zero,0.75f,SpriteEffects.None,0f);text.Y+=lh;}_spriteBatch.End();}
        private SpriteFont? GetTooltipFont(){if(_tooltipFont!=null)return _tooltipFont;try{_tooltipFont=_screenManager.Game.Content.Load<SpriteFont>("Arial24");}catch(InvalidOperationException){return null;}return _tooltipFont;}
        private Texture2D GetTooltipPixel(){if(_tooltipPixel!=null)return _tooltipPixel;_tooltipPixel=new Texture2D(_graphicsDevice,1,1);_tooltipPixel.SetData(new[]{Color.White});return _tooltipPixel;}
    }
}
